version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/db
    container_name: db
    networks:
      - bluebank
    ports:
      - '3306:3306'
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    restart: always

  api_bluebank:
    container_name: api
    build:
      context: .
      dockerfile: api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/api
    networks:
      - bluebank
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
networks:
  bluebank:
    driver: bridge